version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demoauth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=yourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecretyourjwtsecret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: demoauth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: demoauth
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
